version: '3.7'

services: 
  website:
    build: .
    image: website:alpine
    container_name: website
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - system-network

  database:
    image: postgres:alpine
    container_name: database
    volumes:
      - ./docker-compose/database:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=system
      - POSTGRES_PASSWORD=system123
      - POSTGRES_DB=system_db
    networks:
      - system-network

  message:
    image: redis:alpine
    container_name: message
    networks:
      - system-network

volumes:
  postgres_data:

networks: 
  system-network:
    driver: bridge
